### ISSUE TITLE
ansible unarchive directive is looking on local machine, not vagrant box

### ISSUE THREAD

**Issue by shermany** [jplock/devbox#1]
While using devbox only to setup kafka/zookeeper (making use of `skip_tags`), I experienced errors such as the following:

```
TASK: [kafka | Extract kafka] *************************************************
fatal: [default] => input file not found at /Users/seanh/src/devbox/roles/kafka/files/kafka_2.10-0.8.2.1.tgz or /Users/seanh/src/devbox/kafka_2.10-0.8.2.1.tgz
```

I've used devbox plenty of times in the past, although admittedly it's probably been since July.

The error would seem to be because the `unarchive` ansible directive by default looks on the **local** machine, while the `get_url` directive your playbooks use downloads the file to the **remote** machine.

I have no idea how this worked a few months ago for me, after looking at the Ansible docs.

http://docs.ansible.com/ansible/unarchive_module.html
http://docs.ansible.com/ansible/get_url_module.html

The following diff shows what I needed to do to fix this (I made a similar change for ZK):
```
 - name: Extract kafka
-  unarchive: src=kafka_2.10-{{ kafka_version }}.tgz
+  unarchive: src=/usr/local/kafka_2.10-{{ kafka_version }}.tgz
              dest=/usr/local
              creates=/usr/local/kafka_2.10-{{ kafka_version }}
+             copy=no
``` 

I can file a P.R., but I have a feeling I'm missing something here.

Additional info:
```
--> ~/src/devbox
[seanh@steck]$ ansible --version
ansible 1.9.4
  configured module search path = None

--> ~/src/devbox
[seanh@steck]$ vagrant --version
Vagrant 1.7.4

--> ~/src/devbox
[seanh@steck]$
```

**Comment by jplock** [comment]
I think this has been fixed.  Sorry for the long delay, but I never saw this notification until now.  :(
